import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from '../components/Weather'
// import Loader from '../components/Loader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

const[city,setCity] = useState('')  
const[weather,setWeather] = useState({})
// const[loading, setLoading] = useState(false)

const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

const fetchWeather = (e) => {
  e.preventDefault()
  // setLoading(true)

  axios.get(url).then((res) => {
    setWeather(res.data)
    // console.log(res.data)
  })

  setCity('')
  // setLoading(false)
}

// if (loading) {
//  return (<Loader />)
// } else {
  return (
    <>
      <Head>
        <title>Weather Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* overlay */}
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]'/>
      {/* background image */}
      <Image 
      src='https://images.unsplash.com/photo-1553984840-ec965a23cddd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80' 
      fill
      alt='background' 
      // className='object-cover'
      />

      {/* search */}
      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
        <form 
        onSubmit={fetchWeather} 
        className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
          <div>
            <input 
            onChange={(e) => setCity(e.target.value)}
            className='bg-transparent border-none text-white focus:outline-none text-2xl' 
            type="text" 
            placeholder='Search city...' />
          </div>
          <button onClick={fetchWeather}><BsSearch size={25} /></button>
        </form>
      </div>

      {/* weather display */}
    
    {weather.main && <Weather data={weather} />}
    </>
    
  )
  }
// }
